// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkf7utErgv67Lec-PNuS51lL_BcXigiVc',
    appId: '1:24949939011:web:cb31382e8712038d522df6',
    messagingSenderId: '24949939011',
    projectId: 'puzzlepix-30903',
    authDomain: 'puzzlepix-30903.firebaseapp.com',
    storageBucket: 'puzzlepix-30903.firebasestorage.app',
    measurementId: 'G-DDHMHDGHB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYeftlGEUwjAMGIcWxWZm5lxrQ1kBxU8',
    appId: '1:24949939011:android:0c590d8a36f9b6e5522df6',
    messagingSenderId: '24949939011',
    projectId: 'puzzlepix-30903',
    storageBucket: 'puzzlepix-30903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQw_ahJHcdItZsLqn-NHGw16OLswDces',
    appId: '1:24949939011:ios:674ec60eb9460258522df6',
    messagingSenderId: '24949939011',
    projectId: 'puzzlepix-30903',
    storageBucket: 'puzzlepix-30903.firebasestorage.app',
    iosBundleId: 'com.example.puzzlePix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQw_ahJHcdItZsLqn-NHGw16OLswDces',
    appId: '1:24949939011:ios:674ec60eb9460258522df6',
    messagingSenderId: '24949939011',
    projectId: 'puzzlepix-30903',
    storageBucket: 'puzzlepix-30903.firebasestorage.app',
    iosBundleId: 'com.example.puzzlePix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkf7utErgv67Lec-PNuS51lL_BcXigiVc',
    appId: '1:24949939011:web:0b276e0157545e30522df6',
    messagingSenderId: '24949939011',
    projectId: 'puzzlepix-30903',
    authDomain: 'puzzlepix-30903.firebaseapp.com',
    storageBucket: 'puzzlepix-30903.firebasestorage.app',
    measurementId: 'G-Y0E3Y7MG1X',
  );
}
